#!/usr/bin/env sh
set -e

if ! type -p fzf >/dev/null; then
  echo "error: install \`fzf\`(https://github.com/junegunn/fzf) to use this command" >&2
  exit 1
fi
if ! type -p ghq >/dev/null; then
  echo "error: install \`ghq\`(https://github.com/x-motemen/ghq) to use this command" >&2
  exit 1
fi

DEFAULT_USER=$(gh api user -q .login)

REPO=$(gh api graphql --paginate -F owner="${1:-$DEFAULT_USER}" -f query='
query ($owner: String!, $endCursor: String) {
  repositoryOwner(login: $owner) {
    repositories(
      first: 30
      after: $endCursor
    ){
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        nameWithOwner
      }
    }
  }
}
' -q '.data.repositoryOwner.repositories.nodes[].nameWithOwner' | fzf)

if [ $? -ne 0 ];then
  exit 1
fi

ghq get "${REPO}" "${@:2}"
